### ISSUE TITLE
RFC | Proponer diseño para relanzar la pagina

### ISSUE THREAD

**Issue by LeoBorai** [OpenVE/openve.github.com#10]
Viendo el potencial de la comunidad para impulsar el propósito de la organización, se me ocurrió empezar por la pagina que representa a OpenVE haciendo un update en la pagina con el fin de ofrecer mas funcionalidades a la misma que podrían impulsar el desarrollo de la organización _per se_.

## Secciones

- Home
  - Imagen con Logo
- Organización
  - Que es OpenVE
  - Mision de la Organización
  - Código de Conducta
- Colaboradores
  - Muestra de los colaboradores
- Proyectos
 Sección donde se mostrarían los proyectos en cuestion y los detalles del mismo

## Posibles "Features" (RFC)
- Entre otras ideas, pensé que estaría bueno poder mostrar búsquedas laborales de interés y contacto para facilitar una red local de trabajo que impulse a los desarrolladores.

**Comment by davidhdz** [comment]
La página actualmente usa [Jekyll](https://jekyllrb.com/) por debajo, cosa que me parece genial (yo también lo uso en mi página personal). ¿Tienes algún tema en mente que podamos ver? Si no tienes pensado trabajar en un tema ya publicado, podrías mostrar entonces algún boceto.

**Comment by LeoBorai** [comment]
Hey @davidhdz!

Pensaba usar GatsbyJS que se integra bastante bien con GitHub Pages y es opinionado.
Con respecto al diseño pienso empezar algo de cero, podríamos pensar un wireframe para partir de allí!

Este articulo de GatsbyJS y GitHub Pages demuestra la integración, [Link](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/).
